### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by wangzi18** [Tsukimi-Ren/Casualness-Delight#9]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'casualness_delight'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_6854
at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
at com.teamresourceful.resourcefulconfig.common.config.impl.ConfigParser.parseData(ConfigParser.java:43) ~[resourcefulconfig-fabric-1.20.1-2.1.2.jar:?]
at com.teamresourceful.resourcefulconfig.common.config.impl.ConfigParser.parseData(ConfigParser.java:67) ~[resourcefulconfig-fabric-1.20.1-2.1.2.jar:?]
at com.teamresourceful.resourcefulconfig.common.config.impl.ConfigParser.parseConfig(ConfigParser.java:24) ~[resourcefulconfig-fabric-1.20.1-2.1.2.jar:?]
at com.teamresourceful.resourcefulconfig.common.config.impl.ConfigLoaderImpl.registerConfig(ConfigLoaderImpl.java:23) ~[resourcefulconfig-fabric-1.20.1-2.1.2.jar:?]
at com.teamresourceful.resourcefulconfig.common.config.Configurator.registerConfig(Configurator.java:28) ~[resourcefulconfig-fabric-1.20.1-2.1.2.jar:?]
at koala.clearwater.ClearWater.init(ClearWater.java:19) ~[Clear-Water-2.1.jar:?]
at koala.clearwater.fabric.ClearWaterFabric.onInitialize(ClearWaterFabric.java:10) ~[Clear-Water-2.1.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_6854
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 18 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2248 com.va11halla.casualness_delight.registry.BlocksRegistry.get()'
at com.va11halla.casualness_delight.registry.ItemRegistry.lambda$static$3(ItemRegistry.java:28) ~[CasualnessDelight-1.20.1-0.4a-Fabric.jar:?]
at com.va11halla.casualness_delight.registry.ItemRegistry.get(ItemRegistry.java:144) ~[CasualnessDelight-1.20.1-0.4a-Fabric.jar:?]
at com.va11halla.casualness_delight.registry.ItemRegistry.register(ItemRegistry.java:135) ~[CasualnessDelight-1.20.1-0.4a-Fabric.jar:?]
at com.va11halla.casualness_delight.CasualnessDelightFabric.onInitialize(CasualnessDelightFabric.java:14) ~[CasualnessDelight-1.20.1-0.4a-Fabric.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
... 7 more

**Comment by wangzi18** [comment]
game version:fabric-1.20.1
mod version:0.4a

**Comment by KawaiShio** [comment]
Version 0.4c has been fixed
